import "@/styles/globals.css";
import Head from "next/head";
// import styles from "../components/Footer/Footer.scss";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Rastropeludo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url(&apos;https://fonts.googleapis.com/css2?family=Mohave:wght@300;500;600;700&display=swap&apos;);
        </style>
      </Head>
      <Component {...pageProps} />
    </>
  );
}
