import Head from "next/head";
import Header from "@components/Header/Header";
import Hero from "@components/Hero/Hero";
import HomeCTA from "@/components/Home/HomeCTA/HomeCTA";
import Footer from "@components/Footer/Footer";
import Info from "@components/Home/Info/Info";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const homeTitle = "Siguiendo huellas y reuniendo corazones";

  return (
    <div className="tout">
      <Head>
        <title>Rastropeludo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url(&apos;https://fonts.googleapis.com/css2?family=Mohave:wght@300;500;600;700&display=swap&apos;);
        </style>
      </Head>
      <Header />
      <Hero title={homeTitle} />
      <HomeCTA />
      <Info />
      <Footer />
    </div>
  );
}
